services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wcd_eka_patas_group_8
    ports:
      - "3300:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
